replicaCount: 1

image:
  repository: yunlzheng/yunlzheng/spring-sample
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  hosts:
    - spring-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
