replicaCount: 1

image:
  repository: yunlzheng/spring-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - spring-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
